data_ingestion:
  raw_data_dir: "data/raw/" # Where the loaded S3 bucket data gets saved
  raw_test_file: "data/processed/test.csv"
  raw_train_file: "data/processed/train.csv"  
  bucket: "amzn-hotel-res-bucket" # which bucket data is in
  key: "training_data/Hotel Reservations.csv"  # which dir in this bucket the data is in
  train_ratio : 0.8

data_processing:
  proc_data_dir: "data/processed/"
  proc_test_file: "data/processed/test.csv"
  proc_train_file: "data/processed/train.csv"
  categorical_columns:
    - type_of_meal_plan
    - required_car_parking_space
    - room_type_reserved
    - market_segment_type
    - repeated_guest
    - booking_status
  numerical_columns:
    - no_of_adults
    - no_of_children
    - no_of_weekend_nights
    - no_of_week_nights
    - lead_time
    - arrival_year
    - arrival_month
    - arrival_date
    - no_of_previous_cancellations
    - no_of_previous_bookings_not_canceled
    - avg_price_per_room
    - no_of_special_requests
  skewness_threshold : 5
  no_of_top_features : 10
